### ISSUE TITLE
Using ItemDecoration

### ISSUE THREAD

**Issue by 7heaven** [sharish/ShimmerRecyclerView#1]
Not sure why you need to subclass RecyclerView, ViewHolder. I think it's much easier to just using Customize ItemDecoration to achieve that.

**Comment by sharish** [comment]
I have not R&D for this repo's implementation using item decoration. For the question about subclassing RecyclerView or ViewHolder, if I don't subclass, I might need to play with user's own child elements(like drawing shady background, adding shimmering effects and have to provide ViewCompact classes to enable/disabling shimmering views) which I don't want to risk for.  This way I felt usage will be simple. 

I might also be interested in your approach of using ItemDecoration.

Thanks,
Harish

**Comment by 1programmer2dfg3** [comment]
写的不错，建议加上下拉刷新和上拉加载
