### ISSUE TITLE
Cannot Build with Gradle

### ISSUE THREAD

**Issue by inanmadak** [sharish/ShimmerRecyclerView#10]
It says Failed to resolve. Tried both 
compile 'com.github.sharish:ShimmerRecyclerView:v1.0.1'

and compile 'com.github.sharish:ShimmerRecyclerView:1.0.1' (without 'v' before version)

both fails please look into it.

**Comment by sharish** [comment]
Checked with Jitpack v1.0.1 https://jitpack.io/com/github/sharish/ShimmerRecyclerView/v1.0.1/build.log
and everything seems fine.

Are you sure you added jitpack maven source in your gradle As specified in the readme?

```
repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}
```

**Comment by inanmadak** [comment]
No, I had not. I have added and it works now thank you. Sorry for the issue.
