### ISSUE TITLE
Application tag attributes are duplicate in Manifest of library module

### ISSUE THREAD

**Issue by kevalpatel2106** [sharish/ShimmerRecyclerView#13]
While importing this library, I am getting duplicate '**allowBackup**' tag. I don't think that application tag is required in the Manifest of the Library module.

Here is the error:
`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:32:9-36
  	is also present at [com.github.sharish:ShimmerRecyclerView:v1.0.1] AndroidManifest.xml:28:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:28:5-32:19 to override.`

**Comment by kevalpatel2106** [comment]
The issue is fixed in PR #14 .

**Comment by sharish** [comment]
#14 Merged and closing the issue.
