### ISSUE TITLE
Runtime rows not changing.

### ISSUE THREAD

**Issue by tabassumLatif** [sharish/ShimmerRecyclerView#15]
I am trying to change on run time it's not working.

**Comment by sharish** [comment]
I would like to know how you are changing the adapter at runtime? As for as shimmer adapter is considered, it is non-modifiable created within the library and you have no access expect specifying the related layout.

**Comment by tabassumLatif** [comment]
I am using grid with one row and when i change on runtime, 1 row to 2 row then shimmer show 1 row and when adapter populate values then show 2 rows.

I think this is a issue and i can fix it.

**Comment by sharish** [comment]
I assume you can handle yourself and I'm closing the issue.

Thanks,
Harish

**Comment by tabassumLatif** [comment]
use this 
https://github.com/tabassumLatif/ShimmerRecyclerView
