### ISSUE TITLE
Cannot find resource identifier for angle and view holder background

### ISSUE THREAD

**Issue by vincent-paing** [sharish/ShimmerRecyclerView#17]
AS 2.3.2 Stable
Using version 'v1.0.1'

This is how I'm defining the ShimmerRecyclerView in the XML
 ```
<com.cooltechworks.views.shimmer.ShimmerRecyclerView
      android:id="@+id/rv_quests"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:orientation="vertical"
      app:layoutManager="LinearLayoutManager"
      app:shimmer_demo_angle="180"
      app:shimmer_demo_child_count="3"
      app:shimmer_demo_layout="@layout/layout_demo"
      app:shimmer_demo_layout_manager_type="linear_vertical"
      app:shimmer_demo_view_holder_item_background="@android:color/white"
      tools:listitem="@layout/item_quest"
  />
 ```

This is the output I'm getting when I build the app

```
Error:(51) No resource identifier found for attribute 'shimmer_demo_angle' in package 'me.aungkyawpaing.testshimmer'
Error:(51) No resource identifier found for attribute 'shimmer_demo_view_holder_item_background' in package 'me.aungkyawpaing.testshimmer'
Error:(51) No resource identifier found for attribute 'shimmer_demo_angle' in package 'me.aungkyawpaing.testshimmer'
Error:(51) No resource identifier found for attribute 'shimmer_demo_view_holder_item_background' in package 'me.aungkyawpaing.testshimmer'
```

EDIT: Just checked with the inspector. Seems like it's not getting added to attribute list in R, only four attrs were added which are followings:
![inspector](http://i.imgur.com/BcfGAiA.png)

**Comment by veghtomi** [comment]
It happened since these are the new features which were not released. The v1.0.1 is still the old version of the library. @sharish

**Comment by vincent-paing** [comment]
@veghtomi  Oh, I thought it's already released since it's in sample code. My bad. I guess you can close this now?

**Comment by veghtomi** [comment]
@vincent-paing I thing leave it here, so the maintainer can see it.

**Comment by ethanhua** [comment]
@veghtomi  your library is great, i'd like to use it in my project or you can sending a PR. 
https://github.com/ethanhua/Skeleton
Thanks

**Comment by veghtomi** [comment]
@ethanhua thanks. I can send a PR.

**Comment by sharish** [comment]
@vincent-paing You can use the updated release v1.1 and resource errors should not be happening. 

Thanks,
Harish
