### ISSUE TITLE
recyclerView.hideShimmerAdapter() resets the scroll position

### ISSUE THREAD

**Issue by dimgarof** [sharish/ShimmerRecyclerView#18]
When implementing endless RecyclerView scrolling when I call hideShimmerAdapter on the request's callback, it resets the scrolling position.

I had to implement a workaround in order to call hideShimmerAdapter only once

```java
if (page == 1 && recyclerView != null) {
    recyclerView.hideShimmerAdapter();
} 
```

Is this expected?

Thanks

**Comment by sharish** [comment]
If you see [ShimmerRecyclerView.java line 193](https://github.com/sharish/ShimmerRecyclerView/blob/master/shimmer/src/main/java/com/cooltechworks/views/shimmer/ShimmerRecyclerView.java#L193), the hideShimmerAdapter() sets the adapter again which reset the scroll position. You should call hideShimmerAdapter() only if you had already called showShimmerAdapter()

You might need to find which adapter RecyclerView is currently using before calling hideShimmerAdapter().

```
if(recyclerView.getActualAdapter() != recyclerView.getAdapter())  {
   // recycler view is currently holding shimmer adapter so hide it
    recyclerView.hideShimmerAdapter();
}
```

This is also a work around. In next version, hideShimmerAdapter() method will reset the adapter only if showShimmerAdapter() is called.

Thanks,
Harish

**Comment by dimgarof** [comment]
OK, makes sense!
Thanks
