### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by anderscheow** [sharish/ShimmerRecyclerView#19]
![screen shot 2017-09-18 at 11 14 08 am](https://user-images.githubusercontent.com/11788504/30528146-93a5032c-9c62-11e7-8a8f-97009db6f6b7.png)
Getting this when try to run it

**Comment by ViTess** [comment]
@anderscheow this bug is [team-supercharge/ShimmerLayout](https://github.com/team-supercharge/ShimmerLayout), you should give him the issue

**Comment by anderscheow** [comment]
@ViTess alright thanks :D

**Comment by sharish** [comment]
@veghtomi Can you take a look at this issue?

Thanks,
Harish

**Comment by veghtomi** [comment]
@sharish I am already working on it!

**Comment by veghtomi** [comment]
@sharish we checked it and this issue can be closed!

**Comment by sharish** [comment]
Can you leave a note about the issue reason and the resolution. Would be useful in future if similar issues encountered?

Thanks,
Harish

**Comment by veghtomi** [comment]
Basically we figured out it happened on a low-end phone. The lib is said to be memory efficient, but still need to use some of them. According to the OutOfMemoryException, it failed to allocate 3Mb memory and the size of the free memory was 0,5Mb. So that is the reason why it happened.

**Comment by sharish** [comment]
Ok thanks 👍

**Comment by thibal-denver** [comment]
Hi,
this issue also occurs on a Sony Xperia X

<img width="1360" alt="xperiax_issue" src="https://user-images.githubusercontent.com/24322017/31709429-4f8c61d8-b3f2-11e7-886e-34c11deeea09.png">

Thibault
