### ISSUE TITLE
Using this lib on a heterogenous recyclerView

### ISSUE THREAD

**Issue by ronanlima** [sharish/ShimmerRecyclerView#2]
Hi, is there a way to use it on a heterogeneous recyclerView? My recyclerView has 4 types of viewHolder and i would like to use a lib like this.

**Comment by sharish** [comment]
No. The library is targeted for homogeneous layouts. Supporting heterogenous layout may not suit for a library of this kind as it requires weird number of addon parameters like how many different layouts, layout references pointers for each different layout, which layout at what position et al. I would recommend you to have your own custom implementation, may be considering this as a base and implement your own shimmer adapter. 

Thanks,
Harish
