### ISSUE TITLE
Does this library manipulate the actual itemView for shimmering effect or do I need to create two item views, one for showing actual data and one demo view for shimmering 

### ISSUE THREAD

**Issue by kvipul** [sharish/ShimmerRecyclerView#26]
There are more than 6 recycler views in my project and each of them has its own itemview (that we provide in ViewHolder class). So should I provide these already existing itemViews to the attribute "app:demo_layout" or should I create another shimmering views for this attr?
I didn't find any detail regarding this in the docs. Shouldn't library be manipulating the itemView itself to get required view for shimmering effect?

Also what's the use of ShimmerAdapter, ShimmerLayout and ShimmerViewHolder? From the docs it seems, I don't need to use any of these to create shimmer effect.

**Comment by veghtomi** [comment]
@kvipul the simpliest version to do shimmer effect is to use the original [library](https://github.com/team-supercharge/ShimmerLayout). Then you just call startAnim...() and stopShimmerAnim...(). 

This library just simplifies if you want to use it at RecyclerViews. As for your first question, it depends. If you want different loading views you should create new itemviews. However if all of the loading will look like the same, than the same itemView can go to every RecyclerViews.

**Comment by kvipul** [comment]
I get it but do I need to use different itemView for actual ViewHolder and for "app:demo_layout" attr? Suppose if my actual itemView is this -

![image](https://user-images.githubusercontent.com/12947194/34211271-9372ce8e-e5be-11e7-80c4-cf39faa0dca7.png)

And shimmering itemView is this - 
![image](https://user-images.githubusercontent.com/12947194/34211308-a8bae0e2-e5be-11e7-9f18-2544b2bda79c.png)

Since both views are different, do I need to create shimmering itemView separately or library is able to manipule actual item view to create shimmering itemView?

Thanks

**Comment by veghtomi** [comment]
You have to create it. Even in the original and in other libs you have to create it. The lib is only manipulating what views drawn to the canvas. I wrote an [article](https://medium.com/supercharges-mobile-product-guide/shimmerlayout-26978ab53c28) when I created the library, maybe it can help to understand the process of it.

**Comment by veghtomi** [comment]
@kvipul Is your questin answered? If yes, please close the issue.

**Comment by kvipul** [comment]
Yes, thanks for the response.
