### ISSUE TITLE
attributes not found

### ISSUE THREAD

**Issue by uragonda-rajesh** [sharish/ShimmerRecyclerView#27]
<com.cooltechworks.views.shimmer.ShimmerRecyclerView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:demo_child_count="10"
        app:demo_layout="@layout/row_tips_layout"
        app:demo_layout_manager_type="linear_vertical"
        app:shimmer_demo_angle="20"
        android:layout_below="@+id/toolbar"
        android:layout_marginBottom="4dp"
        android:layout_marginLeft="4dp"
        android:layout_marginRight="4dp"
        android:scrollbars="none"
        />

**log error :**
Error:error: attribute 'my.apps.raj.pro:demo_child_count' not found.
Error:error: attribute 'my.apps.raj.pro:demo_layout' not found.
Error:error: attribute 'my.apps.raj.pro:demo_layout_manager_type' not found.

**Comment by sharish** [comment]
Kindly double check the README before raising issue. The attributes are

```
app:shimmer_demo_layout
app:shimmer_demo_layout_manager_type
app:shimmer_demo_child_count
```

-Harish
