### ISSUE TITLE
Shimmer animation RTL

### ISSUE THREAD

**Issue by arashmidos** [sharish/ShimmerRecyclerView#28]
Hi, 
Is there any way to show shimmer animation from right to left instead of default behavior, or I had to change `ShimmerLayout` code?

**Comment by veghtomi** [comment]
@arashmidos there is no way now, but it would be a great feature request.

**Comment by veghtomi** [comment]
Next week I will release `ShimmerLayout` with this feature and after `ShimmerRecyclerView` will be able to use it as well

**Comment by veghtomi** [comment]
@arashmidos feature is added. Probably next week going to be released by @sharish

**Comment by veghtomi** [comment]
@arashmidos the new release with this feature is out!
