### ISSUE TITLE
ShimmerRecyclerView always show one item when layout manager equals "linear_horizontal"

### ISSUE THREAD

**Issue by kaiyan910** [sharish/ShimmerRecyclerView#30]
When applying "linear_horizontal" to the recycleview it always shows one 1 item.
No matter what value I set to "shimmer_demo_child_count".

I think the problem is viewholder_shimmer.xml, as it uses match_parent for width showing a single item will occupy the full width and not be able to show the second item for horizontal recyclerview.

The problem solved when I overrided viewholder_shimmer.xml and set it wrap_content for width.

**Comment by veghtomi** [comment]
@kaiyan910 Thanks for reporting the issue, it will be fixed soon!

**Comment by veghtomi** [comment]
@kaiyan910 Issue is fixed. Probably next week going to be released by @sharish

**Comment by KarmatechMediaworks** [comment]
has the version number been changed, can you let me know the latest version number

**Comment by veghtomi** [comment]
@KarmatechMediaworks the new release it out! Try it.
