### ISSUE TITLE
layoutManager.findLastCompletelyVisibleItemPosition() doesn't work correctly

### ISSUE THREAD

**Issue by mohammadms2008** [sharish/ShimmerRecyclerView#34]
hello. I'm using your library for a project...
it works correctly, but when I set a LinearLayout to ShimmerRecyclerView and then I call findLastCompletelyVisibleItemPosition(), it returns incorrect number even negative numbers.
Could u help me???
Thanks a lot...

**Comment by mohammadms2008** [comment]
It's solved and not about your library...

**Comment by veghtomi** [comment]
@mohammadms2008 sorry for writing back a little late. If it is solved, I am closing the issue!
