### ISSUE TITLE
setDemoShimmerMaskWidth method not found

### ISSUE THREAD

**Issue by vincent-paing** [sharish/ShimmerRecyclerView#36]
Using on v1.3 and it can't find setDemoShimmerMaskWidth function for the ShimmerRecyclerView

**Comment by alejandrorosas** [comment]
Hey @vincent-paing the feature is in master but not on the latest release (`v1.3`), I think that @sharish will release a new version soon 😃

**Comment by alouanemed** [comment]
Any updates to this?
