### ISSUE TITLE
No Scrolling in Shimmer Recycler View

### ISSUE THREAD

**Issue by ParthJadav** [sharish/ShimmerRecyclerView#37]
I was trying to implement your library into my application but I am not able to scroll ShimmerRecyclerView items....???

**Comment by MikeSoft** [comment]
I have the self issued, to solve it, i put the shimmerview inside scrollview in the layout. 

```
        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent">
        <com.cooltechworks.views.shimmer.ShimmerRecyclerView
            android:layout_marginTop="20dp"
            android:id="@+id/list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
             />
        </ScrollView>
```

**Comment by veghtomi** [comment]
@ParthJadav This is a feature, you cannot scroll it. To fix it you can try the code mentioned above, but with NestedScrollView and set the nestedScrollingEnabled method to false on the ShimmerRecyclerView.

The other solution is to use the [ShimmerLayout](https://github.com/team-supercharge/ShimmerLayout) library and implement a RecyclerView.Adapter yourself, so you can manipulate every aspect of it.
