### ISSUE TITLE
How to use this for activities layout

### ISSUE THREAD

**Issue by HasanShaikh** [sharish/ShimmerRecyclerView#7]
Consider i have an activity which has some texts and images. The data is coming from the server so it will take some time to load. Now until the data gets loaded it will show the empty layout. But i want to show shimmer layout until the data gets loaded. So how can i achieve this.

**Comment by IshaanKr** [comment]
The Shimmer feature is for RecyclerVIew.
If you want to use for Layout. Use this library:
https://github.com/facebook/shimmer-android

and to use shimmer on RecyclerView.
Use funtion showShimmerAdapter on RecyclerView.

**Comment by sharish** [comment]
@HasanShaikh The usage of showShimmerAdapter() and hideShimmerAdapter() serves that purpose. You need to call showShimmerAdapter() the moment recyclerview is created and on your API callback method you need to load your adapter and call hideShimmerAdapter(). 

Sample snippet for volley call

```java
String url = "" ; // your api here url here
RequestQueue queue = ; // volley request queue here 
RecyclerView.Adapter adapter = ; // your variant of recycler adapter

ShimmerRecyclerView shimmerRecyclerView = (ShimmerRecyclerView) findViewById(R.id.your_shimmer_recycler_view_id);
shimmerRecyclerView.setAdapter(adapter);
shimmerRecyclerView.showShimmerAdapter();

StringRequest postRequest = new StringRequest(Request.Method.GET, url, 
    new Response.Listener<String>() 
    {
        @Override
        public void onResponse(String response) {
            
            String values[] = response.split(",");
            adapter.setValues(values);
            shimmerRecyclerView.hideShimmerAdapter();
        }
    }, 
    new Response.ErrorListener() 
    {
         @Override
         public void onErrorResponse(VolleyError error) {
             // error
             Log.d("Error.Response", response);

             Toast.makeText(MainActivity.this, "Some api error", Toast.LENGTH_SHORT).show();
       }
    }
) 
queue.add(postRequest);
```

Reopen the issue if it has any bug.

Thanks,
Harish
