### ISSUE TITLE
error unable to build

### ISSUE THREAD

**Issue by Midhilaj** [sharish/ShimmerRecyclerView#9]
Error:(744) Attribute "shape" already defined with incompatible format.
Error:(701) Original attribute defined here.
Error:(744) Attribute "shape" already defined with incompatible format.
Error:(701) Original attribute defined here.
Error:(23, 53) String types not allowed (at 'shape' with value 'linear').
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by kokorambo** [comment]
I have same problem. Can you help me to fix this?

**Comment by sharish** [comment]
The issue fixed in latest release.

```compile 'com.github.sharish:ShimmerRecyclerView:v1.0.1' ```

Thanks,
Harish
